# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import eco_control_pb2 as eco__control__pb2
except ImportError:
    import eco_control_pb2 as eco__control__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eco_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EcoControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlStep = channel.unary_unary(
                '/eco.EcoControlService/ControlStep',
                request_serializer=eco__control__pb2.ControlRequest.SerializeToString,
                response_deserializer=eco__control__pb2.ControlReply.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/eco.EcoControlService/Health',
                request_serializer=eco__control__pb2.HealthRequest.SerializeToString,
                response_deserializer=eco__control__pb2.HealthReply.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/eco.EcoControlService/Heartbeat',
                request_serializer=eco__control__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=eco__control__pb2.HeartbeatReply.FromString,
                _registered_method=True)
        self.AbortSession = channel.unary_unary(
                '/eco.EcoControlService/AbortSession',
                request_serializer=eco__control__pb2.AbortSessionRequest.SerializeToString,
                response_deserializer=eco__control__pb2.AbortSessionReply.FromString,
                _registered_method=True)


class EcoControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ControlStep(self, request, context):
        """Corresponds to the original /api/v1/control/step endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Corresponds to the original /api/v1/health endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Independent plugin heartbeat for session liveness.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortSession(self, request, context):
        """Plugin notification for user-initiated interruption.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EcoControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlStep,
                    request_deserializer=eco__control__pb2.ControlRequest.FromString,
                    response_serializer=eco__control__pb2.ControlReply.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=eco__control__pb2.HealthRequest.FromString,
                    response_serializer=eco__control__pb2.HealthReply.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=eco__control__pb2.HeartbeatRequest.FromString,
                    response_serializer=eco__control__pb2.HeartbeatReply.SerializeToString,
            ),
            'AbortSession': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortSession,
                    request_deserializer=eco__control__pb2.AbortSessionRequest.FromString,
                    response_serializer=eco__control__pb2.AbortSessionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eco.EcoControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eco.EcoControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EcoControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ControlStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eco.EcoControlService/ControlStep',
            eco__control__pb2.ControlRequest.SerializeToString,
            eco__control__pb2.ControlReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eco.EcoControlService/Health',
            eco__control__pb2.HealthRequest.SerializeToString,
            eco__control__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eco.EcoControlService/Heartbeat',
            eco__control__pb2.HeartbeatRequest.SerializeToString,
            eco__control__pb2.HeartbeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eco.EcoControlService/AbortSession',
            eco__control__pb2.AbortSessionRequest.SerializeToString,
            eco__control__pb2.AbortSessionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
